CREATE OR REPLACE FUNCTION getProductByTitle(_title TEXT)
RETURNS SETOF PRODUCTS
AS $$
        SELECT *
        FROM PRODUCTS 
        WHERE INITCAP(TITLE) = INITCAP(_title);
$$ LANGUAGE SQL STRICT IMMUTABLE;