version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.28
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: jack
            password: orbien
            migrations: true
  postgres:
    image: postgres:10.6
    restart: always
    environment:
      POSTGRES_USER: jack
      POSTGRES_PASSWORD: orbien
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
