version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.29
    restart: always
    ports:
    - "5555:5555"
    environment:
      PRISMA_CONFIG: |
        port: 5555
        databases:
          default:
            connector: mysql
            host: 35.187.184.95
            port: 3306
            user: root
            password: toor
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
