version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.28
    restart: always
    ports:
    - "4567:457"
    environment:
      PRISMA_CONFIG: |
        port: 4567
        databases:
          default:
            host: host.docker.internal
            connector: postgres
            host: postgres
            port: 5432
            user: postgres
            password: 1234
            migrations: true
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: